# Generated by Django 3.2.4 on 2022-07-07 07:07

from django.conf import settings
from django.db import migrations, models


def apply_migration(apps, schema_editor):
    roulette = apps.get_model('roulette', 'Roulette')
    # Номер джекпота
    obj, created = roulette.objects.get_or_create(
        value=-1,
        weight=0
    )
    # Остальные номера
    roulette.objects.bulk_create([
        roulette(value=1, weight=20),
        roulette(value=2, weight=100),
        roulette(value=3, weight=45),
        roulette(value=4, weight=70),
        roulette(value=5, weight=15),
        roulette(value=6, weight=140),
        roulette(value=7, weight=20),
        roulette(value=8, weight=20),
        roulette(value=9, weight=140),
        roulette(value=10, weight=45),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('weight', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Номер рулетки',
                'verbose_name_plural': 'Номера рулетки',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False)),
                ('used_numbers', models.ManyToManyField(related_name='rounds', to='roulette.Roulette')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Раунд',
                'verbose_name_plural': 'Раунды',
            },
        ),
        migrations.RunPython(apply_migration)
    ]